services:
  db:
    image: mysql:8.4
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - wpdbs

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      #PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 512MB
      MEMORY_LIMIT: 1024M
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
        - /sessions
        - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
      - wpdbs

volumes:
  db:
  phpmyadmin:

networks:
  wpdbs:
    driver: bridge
